config/routes.rb
Rails.application.routes.draw do
  
  resources :notices
  
  get 'principal/index'

  root 'static_pages#home2'
  
  get 'event/new'

  get 'event/edit'

  get 'event/delete'

  devise_for :users, controllers: {registrations: 'registrations'}
  
  resources :users, only: [:index, :show, :edit,:update,:destroy]
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'contacto/forn_contactenos'
  
  get '/administrador' => 'static_pages#admin'  #admin es el nombre del archivo

  
  get '/home' => 'static_pages#home'
  
  get '/egresados' => 'static_pages#egresados'
  get '/acercade' => 'static_pages#about'
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'principal/index'
  get 'evento' => 'evento#listar'
  get 'evento/nuevo' => 'evento#nuevo'
  post 'evento/nuevo' => 'evento#nuevo'
  post 'evento/crear' => 'evento#crear'
  get 'evento/crear' => 'evento#crear'
  get 'evento/eliminar' => 'evento#eliminar'
  post 'evento/eliminar' => 'evento#eliminar'
  get 'evento/mostrar'
  get 'evento/modificar' => 'evento#modificar'
  post 'evento/modificar' => 'evento#modificar'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home2
  end
  
  def contactenos
  end
  
  def about
  end
  
  def egresados
  end
  
  def admin
    if !current_user 
        #flash.now[:error] = 'Acceso no permitido'
        redirect_to root_path, alert: 'Acceso Restringido.'
    elsif current_user.role!=1
        #flash.now[:error] = 'Acceso no permitido2'
        redirect_to root_path, alert: 'Acceso Restringido.'
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Acerca del Tecn&oacute;logo") %>

<div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-md-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Acerca del Tecn&oacute;logo</h2>
                    <p class="lead">
                        La carrera de “Tecnólogo en Informática” constituye parte de una oferta educativa llamada 
                        genéricamente “Educación Tecnológica Terciaria”; ofrecida conjuntamente por la
                         <a href="http://www.universidad.edu.uy/">Universidad de la República (UdelaR)</a> 
                        y la <a href="http://www.anep.edu.uy/anep/">Administración Nacional de la Educación Pública (ANEP)</a>. 
                        <br>
                        El Tecnólogo en Informática 
                        sede Paysandú se inicia en mayo del 2009 y es la única sede habilitada al norte del Río Negro.
                        Se ubica dentro del Puerto Regional Digital Paysandú Innova (IdP).
                        <br>
                        Su objetivo es la formación de profesionales capacitados para actuar en la realización, puesta 
                        en marcha, mantenimiento y administración de sistemas informáticos para afrontar las 
                        necesidades y demandas del sector productivo, así como contribuir al desarrollo de la 
                        sociedad.
                    </p>
                </div>
                <br>
                <br>
                
                <div class="col-md-6">
                    
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" class="img-responsive" src="../Inova.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="/nave.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="salon_antel.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="nave.jpg" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    
                </div>
                
            </div>

        </div>

</div>

app/views/static_pages/admin.html.erb
<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/administrador">
                        Administrador
                    </a>
                </li>
                <li>
                    <a href="#">Inicio</a>
                </li>
                <li>
                    <%= link_to 'Crear Noticia', new_notice_path %>
                    
                </li>
                <li>
                    <%= link_to 'Ver Todos Los Usuarios', users_path %>
                </li>
                <li>
                    <%= link_to 'Ver Usuarios Inhabilitados', users_path(approved:'false') %>
                </li>
                 <li>
                <%= link_to 'Agregar eventos', principal_index_path %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Panel de control Administrador</h1>
                        <p>
                            <!--iframe src="events/index.html.erb"></iframe-->
                            
                        </p>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Barra Lateral</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
    <!--esta para que no aparezca el footer-->
    <style>
        .footer{
            display:none;
        }
    </style>

app/views/static_pages/contactenos.html.erb
<% provide(:title, "Contacto") %> 

    
    <div class="contaSty">
        <div class="container">            
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Cont&aacute;ctenos</h2>
                    <h3 class="section-subheading text-muted">P&oacute;ngase en contacto con el tecn&oacute;logo.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    
                    <div class="form-group">
                       <input type="text" class="form-control" placeholder="Ingrese nombre *" id="name" required="" data-validation-required-message="Por favor ingrese su nombre.">
                        <p class="help-block text-danger"></p>
                    </div>
                    
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Ingrese e-mail *" id="email" required="" data-validation-required-message="Por favor ingrese su e-mail.">
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input type="tel" class="form-control" placeholder="Ingrese asunto *" id="asunto" required="" data-validation-required-message="Por favor ingrese su asunto.">
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <textarea class="form-control" placeholder="Ingrese mensaje *" id="message" required="" data-validation-required-message="Por favor ingrese el mensaje." style="resize:none;"></textarea>
                        <p class="help-block text-danger"></p>
                        <div class="col-lg-12 text-center btnmap">
                            <h5 class="section-subheading text-muted">Coordinadora: <font color="Black">Ana Iruleguy</font></h5>
                            <div  style="margin-top: 5px;">
                                <i class="glyphicon glyphicon-envelope">
                                </i> tipay.2009@gmail.com
                            </div>
                            <div  style="margin-top: 5px;">
                                <i class="glyphicon glyphicon-home">
                                    
                                </i> Leandro G&oacute;mez y 33 Orientales S/N.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                    <div id="success"></div>
                    <button type="submit" class="btn btn-default btn-lg">
                        <i class="glyphicon glyphicon-envelope"></i>
                        <span class="network-name">Enviar</span>
                    </button>
                </div>
            </div>
        </div>
        
        
                <div class="mapa">
                    <!-- Embedded Google Map -->
                
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3371.7636080539423!2d-58.085891419498715!3d-32.318204022875015!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0xcee1009272710a0c!2sCentro+MEC+Paysand%C3%BA!5e0!3m2!1ses-419!2suy!4v1429590955312" width="100%" height="500px" frameborder="0" style="border:0"></iframe>
                        
                </div>
                
        
</div>

app/views/static_pages/egresados.html.erb
<div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Perfil del egresado: </h2>
                    <p class="lead">El Tecnólogo en Informática será capaz de desarrollar sistemas de pequeño y mediano porte y
                                    podrá integrarse a grupos de desarrollo de proyectos de porte superior. 
                                    Contará con la habilidad de construir y evaluar soluciones informáticas abarcando las tareas de 
                                    construcción, pruebas y documentación, integrando eventualmente distintas tecnologías. 
                                    Poseerá habilidades de comunicación, tanto para presentar sus soluciones dentro del área, como
                                    para interactuar con profesionales de otras áreas y público en general. Esto incluye la capacidad
                                    de trabajar en equipo en todos los aspectos de su actividad.
                                    <br>
                                    <br>
                                    Al egresar de la carrera el Tecnólogo en Informática habrá adquirido una formación en las áreas fundamentales de la computación
                                    con una profundización en alguna subárea de la misma. Dicha formación incluirá aspectos teóricos fundamentales y una fuerte componente práctica, incluyendo el manejo de tecnologías actualizadas. También incluirá la experiencia de desarrollo de una solución informática a un problema real, preferentemente realizada en el contexto de una pasantía en una empresa (Proyecto/Pasantía).
                                    <br>
                                    <!--a target="_blank" href="http://www.antel.com.uy">Antel </a> o quizas no por las <a target="_blank" href="http://www.google.com">Peliculas</a-->
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="/pasillo2.jpg" alt="">
                </div>
                
            </div>

        </div>
        <!-- /.container -->

    </div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home'); %>

<nav class="navbar navbar-fixed-top transparente">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("logo.png", alt: " "),'/' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li>
              </li>
              <li>
                  <a href="/acercade">Acerca del Tecn&oacute;logo</a>
              </li>
              <li>
                  <a href="/contactenos">Contacto</a>
              </li>
          </ul>
      </div>
      <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<header>
    <div id="carousel" class="csslider1 autoplay ">
    	<input name="cs_anchor1" id="cs_slide1_0" type="radio" class="cs_anchor slide">
    	<input name="cs_anchor1" id="cs_slide1_1" type="radio" class="cs_anchor slide">
    	<input name="cs_anchor1" id="cs_slide1_2" type="radio" class="cs_anchor slide">
    	<input name="cs_anchor1" id="cs_slide1_3" type="radio" class="cs_anchor slide">
    	<input name="cs_anchor1" id="cs_play1" type="radio" class="cs_anchor" checked="">
    	<input name="cs_anchor1" id="cs_pause1_0" type="radio" class="cs_anchor pause">
    	<input name="cs_anchor1" id="cs_pause1_1" type="radio" class="cs_anchor pause">
    	<input name="cs_anchor1" id="cs_pause1_2" type="radio" class="cs_anchor pause">
    	<input name="cs_anchor1" id="cs_pause1_3" type="radio" class="cs_anchor pause">
    	<ul>
    		<li class="cs_skeleton"><img src="http://www.fing.edu.uy/sites/default/files/cupDSC05907_0.jpg" style="width: 100%;"></li>
    		<li class="num0 img slide"> <img src="http://www.fing.edu.uy/sites/default/files/cupDSC05881_0.jpg" ></li>
    		<li class="num1 img slide"> <img src="http://servicios.fondosolidaridad.org.uy/Portal/faces/resources/img/logo_portal.png" ></li>
    		<li class="num2 img slide"> <img src="https://comparabien-default.s3.amazonaws.com/field/image/estudiantes-2.jpg" ></li>
    		<li class="num3 img slide"> <img src="http://www.unilab.edu.br/wp-content/uploads/2012/06/laboratorio-informatica-Unilab.jpg" ></li>
    	</ul>
    	<div class="cs_engine"></div>
	</div>
</header>

<!-- Page Content -->
    <div class="row">
        <div class="col-lg-12">
            <h1>Full Slider by Start Bootstrap</h1>
            <p>The background images for the slider are set directly in the HTML using inline CSS. The rest of the styles for this template are contained within the <code>full-slider.css</code>file.</p>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </div>

    <hr>
    
    <footer class="">
        <div class="">
            
        </div>
    </footer>

<!-- /.container -->

app/views/static_pages/home2.html.erb
<script>
    new WOW().init();
</script>
    
<!-- Header -->
    <a name="about"></a>
    
        
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
              <!-- Indicators -->
              
              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                <div class="item active">
                  <img src="/lab3.1.jpg" alt="...">
                  <div class="carousel-caption">
                        <div class="intro-message">
                            <h1>Tecn&oacute;logo en Inform&aacute;tica</h1>
                            <h3>Paysand&uacute;</h3>
                        </div>
                  </div>
                </div>
                <div class="item">
                  <img src="/lab2.jpg" alt="...">
                  <div class="carousel-caption">
                      <div class="intro-message">
                        <h1>Tecn&oacute;logo en Inform&aacute;tica</h1>
                            <h3>Paysand&uacute;</h3>
                        </div>
                  </div>
                </div>
                
              </div>
            
            </div>
        
            
        
        
    
    <!-- Page Content -->

    <a name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Ambiente:<br>Salones y Laboratorios</h2>
                    <p class="lead">Espacios amplios, limpios e iluminados, equipados con lo necesario para generar un ambiente favorable al estudio. Computadoras, Smart TVs, proyectores, 
                                    escritorios y todo lo que el estudiante puede llegar a necesitar
                        <br>
                        <br>
                        <a href="/acercade" class="btn btn-default btn-md">
                                <i class="fa fa-university fa-fw"></i> 
                                <span class="network-name">
                                    Ver M&aacute;s
                                </span>
                        </a>
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive sombra wow fadeInRight animated" data-wow-delay="0.5s" data-wow-duration="0.15s" src="/lab2.jpg" alt="">
                </div> 
            </div>

        </div>
        <!-- /.container src="http://pngimg.com/upload/tablet_PNG8565.png" -->

    </div>

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Requisitos de Ingreso</h2>
                    <p class="lead"> 
                        Pueden ingresar a la carrera tanto egresados del “Bachillerato Tecnol&oacute;gico de Procesamiento y Mantenimiento Inform&aacute;tico”, de la “Enseñanza Media Tecnol&oacute;gica en Inform&aacute;tica” y de los “Bachilleratos de Educaci&oacute;n Secundaria” que habiliten el ingreso a la Facultad de Ingenier&iacute;a.
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive sombra wow fadeInLeft animated" data-wow-delay="0.5s" data-wow-duration="0.15s" src="/documents.jpg" alt="">
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
    <div class="content-section-a">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Perfil del egresado: </h2>
                    <p class="lead">El Tecn&oacute;logo en Inform&aacute;tica ser&aacute; capaz de desarrollar sistemas de pequeño y mediano porte y
                                    podr&aacute; integrarse a grupos de desarrollo de proyectos de porte superior. 
                                    <br>
                                    <br>
                                    Contar&aacute; con la habilidad de construir y evaluar soluciones inform&aacute;ticas abarcando las tareas de 
                                    construcci&oacute;n, pruebas y documentaci&oacute;n, integrando eventualmente distintas tecnolog&iacute;as. 
                                    <br>
                                    <br>
                                    Poseer&aacute; habilidades de comunicaci&oacute;n, tanto para presentar sus soluciones dentro del &aacute;rea, como
                                    para interactuar con profesionales de otras &aacute;reas y p&uacute;blico en general. Esto incluye la capacidad
                                    de trabajar en equipo en todos los aspectos de su actividad.
                                    <br>
                                    <br>
                                    <a href="/egresados" class="btn btn-default btn-md">
                                        <i class="fa fa-university fa-fw"></i> 
                                        <span class="network-name">
                                            Ver M&aacute;s
                                        </span>
                                    </a>
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive sombra wow pulse animated" data-wow-delay="300ms" data-wow-iteration="4" data-wow-duration="2s" src="/bannerTecno.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

    <a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Ven&iacute; a estudiar al Tecn&oacute;logo en Paysand&uacute;</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="/contacts" class="btn btn-primary btn-lg"><i class="fa fa-envelope fa-fw"></i> <span class="network-name">Contacto</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

   </div>