config/routes.rb
Rails.application.routes.draw do
  
  resources :notices
  
  get 'principal/index'

  root 'static_pages#home2'
  
  get 'event/new'

  get 'event/edit'

  get 'event/delete'

  devise_for :users, controllers: {registrations: 'registrations'}
  
  resources :users, only: [:index, :show, :edit,:update,:destroy]
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'contacto/forn_contactenos'
  
  get '/administrador' => 'static_pages#admin'  #admin es el nombre del archivo

  
  get '/home' => 'static_pages#home'
  
  get '/egresados' => 'static_pages#egresados'
  get '/acercade' => 'static_pages#about'
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'principal/index'
  get 'evento' => 'evento#listar'
  get 'evento/nuevo' => 'evento#nuevo'
  post 'evento/nuevo' => 'evento#nuevo'
  post 'evento/crear' => 'evento#crear'
  get 'evento/crear' => 'evento#crear'
  get 'evento/eliminar' => 'evento#eliminar'
  post 'evento/eliminar' => 'evento#eliminar'
  get 'evento/mostrar'
  get 'evento/modificar' => 'evento#modificar'
  post 'evento/modificar' => 'evento#modificar'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
      
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  
  before_save :set_admin
  
  
  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end
  
  
  
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
  
  
  private
  def set_admin
    if User.count < 2
      self.role = 1
      self.approved=true
    end
  end
  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        if !current_user 
            #flash.now[:error] = 'Acceso no permitido'
            redirect_to root_path, alert: 'Acceso Restringido.'
        elsif current_user.role!=1
            #flash.now[:error] = 'Acceso no permitido2'
            redirect_to root_path, alert: 'Acceso Restringido.'
        end
        
        if params[:approved] == "false"
            #@users = User.find_by_approved(false)
            @users = User.where(approved: false)
        else
            @users = User.all
        end
        
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def edit
        if !current_user 
            #flash.now[:error] = 'Acceso no permitido'
            redirect_to root_path, alert: 'Acceso Restringido.'
        elsif current_user.role!=1
            #flash.now[:error] = 'Acceso no permitido2'
            redirect_to root_path, alert: 'Acceso Restringido.'
        end
        @user = User.find(params[:id])
    end
    
    def update 
      @user = User.find(params[:id]) 
      if @user.update(user_param)
         redirect_to user_url(@user.id), :flash => { :success => "Usuario modificado correctamente" }
      else
        redirect_to user_url(@user.id), :error => { :error => "No se ha podido editar el usuario" }
      end
    end
    
    def destroy
        @user = User.find(params[:id])
        if @user.destroy
                redirect_to user_url(current_user.id), :flash => { :success => "Usuario Borrado Satisfactoriamente" }
        end
    end
    
    
    protected
    def update_resource(resource, params)
        resource.update_without_password(params)
    end
    
    private
    def user_param
        params.require(:user).permit(:name, :last_name,:approved)
    end
    
    private
    def admin
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar Sesion", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registro de Usuario", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Olvido su contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>