config/routes.rb
Rails.application.routes.draw do
  
  resources :notices
  
  get 'principal/index'

  root 'static_pages#home2'
  
  get 'event/new'

  get 'event/edit'

  get 'event/delete'

  devise_for :users, controllers: {registrations: 'registrations'}
  
  resources :users, only: [:index, :show, :edit,:update,:destroy]
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'contacto/forn_contactenos'
  
  get '/administrador' => 'static_pages#admin'  #admin es el nombre del archivo

  
  get '/home' => 'static_pages#home'
  
  get '/egresados' => 'static_pages#egresados'
  get '/acercade' => 'static_pages#about'
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'principal/index'
  get 'evento' => 'evento#listar'
  get 'evento/nuevo' => 'evento#nuevo'
  post 'evento/nuevo' => 'evento#nuevo'
  post 'evento/crear' => 'evento#crear'
  get 'evento/crear' => 'evento#crear'
  get 'evento/eliminar' => 'evento#eliminar'
  post 'evento/eliminar' => 'evento#eliminar'
  get 'evento/mostrar'
  get 'evento/modificar' => 'evento#modificar'
  post 'evento/modificar' => 'evento#modificar'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
      
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  
  before_save :set_admin
  
  
  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end
  
  
  
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
  
  
  private
  def set_admin
    if User.count < 2
      self.role = 1
      self.approved=true
    end
  end
  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        if !current_user 
            #flash.now[:error] = 'Acceso no permitido'
            redirect_to root_path, alert: 'Acceso Restringido.'
        elsif current_user.role!=1
            #flash.now[:error] = 'Acceso no permitido2'
            redirect_to root_path, alert: 'Acceso Restringido.'
        end
        
        if params[:approved] == "false"
            #@users = User.find_by_approved(false)
            @users = User.where(approved: false)
        else
            @users = User.all
        end
        
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def edit
        if !current_user 
            #flash.now[:error] = 'Acceso no permitido'
            redirect_to root_path, alert: 'Acceso Restringido.'
        elsif current_user.role!=1
            #flash.now[:error] = 'Acceso no permitido2'
            redirect_to root_path, alert: 'Acceso Restringido.'
        end
        @user = User.find(params[:id])
    end
    
    def update 
      @user = User.find(params[:id]) 
      if @user.update(user_param)
         redirect_to user_url(@user.id), :flash => { :success => "Usuario modificado correctamente" }
      else
        redirect_to user_url(@user.id), :error => { :error => "No se ha podido editar el usuario" }
      end
    end
    
    def destroy
        @user = User.find(params[:id])
        if @user.destroy
                redirect_to user_url(current_user.id), :flash => { :success => "Usuario Borrado Satisfactoriamente" }
        end
    end
    
    
    protected
    def update_resource(resource, params)
        resource.update_without_password(params)
    end
    
    private
    def user_param
        params.require(:user).permit(:name, :last_name,:approved)
    end
    
    private
    def admin
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="form-horizontal">
<%= form_for @user do |f| %>

    <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_field :name, autofocus: true, class: 'form-control'  %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :last_name, class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.text_field :last_name, autofocus: true, class: 'form-control'  %>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.label :approved, "Aprobado", class: 'col-sm-2 control-label'  %>
        <div class="col-sm-6">
            <%= f.radio_button :approved, true %> <%= f.label :approved, "Si" %>
            <%= f.radio_button :approved, false %> <%= f.label :approved, "No" %>
        </div>
    </div>
        
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit "Actualizar", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>    
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <%= button_to "Borrar Este Usuario", registration_path(@user), data: { confirm: "Estás seguro?" }, method: :delete, class: 'btn btn-danger btn-md' %>
        </div>
    </div>


</div>

app/views/users/index.html.erb
<div class="container" style="margin-top: 50px;">
    <div class="users row">
        <% @users.each do |user| %>
        <div class="panel panel-default">
            <%= link_to user_path(user) do %>
            <div class="panel-body">
                <%= image_tag(user.avatar.url(:thumb)) %>
                <p><%= user.full_name %></p>
                <p><%= link_to "Edit", edit_user_path(user) %></p>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>


</div>

<style>
    footer{
        bottom:0;
    }
</style>

app/views/users/show.html.erb
<style>
            
            tbody tr {
                cursor: pointer;
            }
            
            table {
                margin-top: 20px;
            }
</style>
<div class="container-fluid">
    <div class="row" style="margin-top:50px;">
        <div class="col-xs-10 col-md-offset-1" id="wrapper">
            <div class="row" id="main">
                    <div class="col-xs-10">
                        <div class="row" id="main">
                            <div class="panel panel-info" id="ipanelperfil">
                                <div class="panel-heading">
                                    Perfil
                                </div>
                                <div class="panel-body">
                                        <div class="row">
                                            <div  class="col-xs-4">
                                                <%= image_tag(@user.avatar.url(:thumb)) %>
                                                
                                            </div>
                                            <div class="col-xs-8">
                                                <ul class="list-group">
                                                    <li class="list-group-item">
                                                        Nombre: <%=@user.name%>
                                                    </li>
                                                    <li class="list-group-item">
                                                        Apellido: <%=@user.last_name%>
                                                    </li>
                                                    <li class="list-group-item">
                                                        Email: <%=@user.email%>
                                                    </li>
                                                    <li class="list-group-item">
                                                        Contacto: <%=@user.date_of_birth%>
                                                    </li>
                                                </ul>
                                                <%= link_to "Regresar", :back, class: 'btn btn-default btn-md' %>
                                            </div>
                                            
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>  
                </div>
        </div>
    </div>
</div>

<style>
    footer{
        bottom:0;
    }
</style>