config/routes.rb
Rails.application.routes.draw do
  
  resources :notices
  
  get 'principal/index'

  root 'static_pages#home2'
  
  get 'event/new'

  get 'event/edit'

  get 'event/delete'

  devise_for :users, controllers: {registrations: 'registrations'}
  
  resources :users, only: [:index, :show, :edit,:update,:destroy]
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'contacto/forn_contactenos'
  
  get '/administrador' => 'static_pages#admin'  #admin es el nombre del archivo

  
  get '/home' => 'static_pages#home'
  
  get '/egresados' => 'static_pages#egresados'
  get '/acercade' => 'static_pages#about'
  
  get '/contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]
  
  get 'principal/index'
  get 'evento' => 'evento#listar'
  get 'evento/nuevo' => 'evento#nuevo'
  post 'evento/nuevo' => 'evento#nuevo'
  post 'evento/crear' => 'evento#crear'
  get 'evento/crear' => 'evento#crear'
  get 'evento/eliminar' => 'evento#eliminar'
  post 'evento/eliminar' => 'evento#eliminar'
  get 'evento/mostrar'
  get 'evento/modificar' => 'evento#modificar'
  post 'evento/modificar' => 'evento#modificar'
  

end

app/views/layouts/_cabezal.html.erb
<!--Este cabezal es el cl&aacute;sico-->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("logo.png", alt: " "), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            
            <li>
                <a href="#about">Acerca de</a>
            </li>
            <li>
                <a href="#services">Servicios</a>
            </li>
            <li>
                <a href="#contact">Contacto</a>
            </li>
                
            <% if current_user %>
                <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
                <li><%= link_to 'Editar Perfil',edit_user_registration_path %></li>
                <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <% else %>
                <li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_cabezal2.html.erb
<!-- COMIENZO DE HEADER -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logo.png", alt: " "), root_path,  class: "wow pulse animated" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                
                <% if current_user %>    
                    <% if current_user.role==1 %>
                        <li>    
                            <a href="/administrador">Panel Administrador</a>
                        </li>
                         <!--li>
                            <%#= link_to 'Members', users_path %>
                        </li-->
                    <% else %>
                        <li>    
                            <%= link_to 'Noticias', notices_path  %>
                        </li>
                    <%end%>
                    
                <%end %>
                
                
                <li>
                    <a href="/acercade">Tecn&oacute;logo</a>
                </li>
                <li>
                    <a href="/contacts">Contacto</a>
                </li>
                
                
                <% if current_user %>
                    <li>
                        <form class="navbar-form navbar-right">
                            
                        </form>
                    </li>
                    <li>
                        <li><%= link_to 'Editar Perfil' ,edit_user_registration_path %></li>
                        <%#= link_to 'Editar Perfil' , edit_user_registration_path %>
                    </li>
                    
                    <li>
                        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
                    </li>
                    
                    <li class="round-image-50">
                        <%= image_tag(current_user.avatar.url(:thumb)) %>
                    </li>

                <% else %>
                    <li>
                        <a href="#myModalIn" data-toggle="modal"><span class="glyphicon glyphicon-log-in"></span> Entrar</a>
                    </li>
                    <li>
                        <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
                            <a href="#myModalSignUp" data-toggle="modal"><span class="glyphicon glyphicon-plus-sign"></span> Registrar</a>
                        <% end -%>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav> <!--Fin de HEADER-->


   
    <!-- Modal HTML -->
      <div id="myModalOut" class="modal fade">

          <div class="modal-dialog">

              <div class="modal-content">

                  <div class="modal-header">

                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                      <h4 class="modal-title">Confirmacion</h4>

                  </div>

                  <div class="modal-body">

                      <p>Est&aacute; seguro que desea Cerrar sesi&oacute;n?</p>

                  </div>

                  <div class="modal-footer">

                      <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>

                      <input type="submit" value="Log out" id="logoutUP" name="logoutUP" class="form-control btn btn-danger">

                  </div>

              </div>

          </div>

      </div>
    
    
    <!--Modal de Log In-->
    <div id="myModalIn" class="modal fade">
    
      <div class="modal-dialog">
    
          <div class="modal-content">
    
              <div class="modal-header">
    
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    
                  <h4 class="modal-title">Iniciar Sesi&oacute;n</h4>
    
              </div>
                <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>
              <div class="modal-body">
                  
                <!--Prepended text-->
                <div class="form-group">
                  <div class="col-md-8 col-md-offset-2">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                      <%= f.email_field :email, autofocus: true , required:"", placeholder:'E-mail', type:'email' ,class: "form-control" %>
                    </div>
                  </div>
                </div>
                
                <!--Prepended text-->
                <div class="form-group">
                  <div class="col-md-8 col-md-offset-2">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                          <%= f.password_field :password, autocomplete: "off", required:"", placeholder:'Contraseña' ,class: "form-control" %>
                    </div>
                  </div>
                </div>
                    
                    <% if devise_mapping.rememberable? -%>
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="input-group">
                                    <%= f.check_box :remember_me %>
                                    <%= f.label :remember_me, "Recúerdame" %>
                                </div>
                            </div>
                        </div>
                      <% end -%>
               
                    </div>
    
              <div class="modal-footer">
    
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    
                  <%= f.submit "Ingresar", class: 'btn btn-primary' %>
    
              </div>
            <% end %>
          </div>
    
      </div>
    
    </div>
    
    <!-- Modal de registro -->
    <div id="myModalSignUp" class="modal fade">

          <div class="modal-dialog">

              <div class="modal-content">

                  <div class="modal-header">
                      
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      
                      <button type="button" class="close" data-toggle="tooltip" data-placement="left" title="La contraseña y la confirmación deben tener mínimo 8 caracteres." data-original-title="" style="margin-right:2%;"><i class="fa fa-info-circle"></i></button>

                      <h4 class="modal-title">Registro de Usuario</h4>

                  </div>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'form-horizontal'}) do |f| %>
                  
                
                    <!--el cuerpo del modal-->
                    
                    <div class="modal-body">

                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2">
                                <div class="input-group">
                                  <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                    <%= f.text_field :name, required:"", placeholder:"Nombre", class: "form-control",autofocus: true %>
                                </div>
                            </div>
                        </div>
                    </div>
                      
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                    <%= f.text_field :last_name, required:"", placeholder:"Apellido", class: "form-control",autofocus: true %>
                                </div>
                            </div>
                        </div>
                    </div>
                      
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                                    <%= f.email_field :email, required:"", placeholder:"E-mail", class: "form-control", autofocus: true %>
                                    </div>
                            </div>
                        </div>
                    </div>

                      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
                      <% end %>
                    
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2"> 
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                                    <%= f.password_field :password, required:"", placeholder:"Contraseña",autocomplete: "off", class: "form-control" %>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2"> 
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                                    <%= f.password_field :password_confirmation,  required:"", placeholder:"Confirmar Contraseña", autocomplete: "off", class: "form-control" %>
                                </div>
                            </div>
                        </div>
                    </div>

                  </div>

                    <div class="modal-footer">
    
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            
                        <%= f.submit "Registrar", class: "btn btn-primary" %>
                    </div>
                  <% end %>

              </div>

          </div>

      </div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <p class="text-center">
            <%= value %>
        </p>
    </div>
<% end %>


<script>
    $('.alert').fadeOut(20000);
</script>

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <footer class="footer" >
        
        <div class="container ">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <%= link_to "Home", root_path %>
                            
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">Nosotros</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="/acercade">Tecn&oacute;logo</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="/contacts">Contacto</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Tecn&oacute;logo en Inform&aacute;tica Paysand&uacute; 2015. All Rights Reserved</p>
                </div>
            </div>
        </div>
        
    </footer>
    

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
        <title>TIP</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        
        <style>
          body { padding-top: 50px; }
        </style>

    </head>
    
  <body>
  
    <%= render 'layouts/cabezal2' %>
    <%= render 'layouts/flash_messages' %>
  
  <%= yield %>
  
  <%= render 'layouts/footer' %>
  
  </body>
  <script>
    Pace.on("done", function(){
    $(".cover").fadeOut(2000);
});
  </script>
</html>